name: Deploy VuePress to GitHub Pages

on:
  push:
    branches:
      - master # Trigger deployment when the main branch is updated (update as per your default branch)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use an appropriate Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the VuePress site
      - name: Build VuePress site
        run: npm run docs:build # Ensure your `package.json` has "docs:build" as the build script

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist # Adjust this path if your VuePress output is elsewhere
          cname: docs.qloapps.com
